security:
    encoders:
        App\Entity\User: bcrypt
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        database_users:
            entity:
                class: App\Entity\User
                property: username
    access_control:
        - path: ^/(login|register)
          role: IS_AUTHENTICATED_ANONYMOUSLY
        - path: ^/
          role: ROLE_USER
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
            logout: ~
            security: true
            anonymous: true
